[project]
name = "examples"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.0",
    "matplotlib>=3.10.3",
    "pyqt6>=6.9.1",
    "tqdm>=4.67.1",
    "turbulent-propagation[cuda12]",
]

[tool.uv.sources]
turbulent-propagation = { workspace = true }
